#Primary stat: 0 -- Strength, 1 -- Agility, 2 -- Intelligence
#Alignment: 0 -- Radiant, 1 -- Dire
create table heroStats(
	Armor real,
	HP integer,
	BaseAgi integer,
	MoveSpeed integer,
	CastSwing real,
	PrimaryStat integer,
	Legs integer,
	AttackSwing real,
	Turnrate real,
	ProjectileSpeed integer,
	NightVision integer,
	DayVision integer,
	BaseAttackTime real,
	AttackPoint real,
	MinDmg integer,
	Name text,
	BaseInt integer,
	Patch text,
	Mana integer,
	Range integer,
	ManaRegen real,
	HPRegen real,
	jankdota_id integer,
	MaxDmg integer,
	AgiGain real,
	CastPoint real,
	BaseStr integer,
	IntGain real,
	Alignment integer,
	StrGain real
);